name: Sync CSPROJ Version
description: Synchronize a CSPROJ file with a version.txt file.
inputs:
  branch:
    required: true
  csproj-path:
    required: true
  version-file-path:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: refs/heads/${{ inputs.branch }}

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: cd $GITHUB_ACTION_PATH && npm ci

    - name: Sync version
      shell: bash
      id: sync
      run: |
        cd $GITHUB_ACTION_PATH
        npx tsx sync-version.ts ${{ inputs.csproj-path }} ${{ inputs.version-file-path }} > res.txt
        res=$(< res.txt)
        echo "$res"
        echo "result=$res" >> $GITHUB_OUTPUT

    - name: Test
      shell: bash
      run: |
        echo "${{ toJSON(steps.sync.outputs.result) }}"
        echo "${{ fromJSON(steps.sync.outputs.result).file_updated }}"
        echo "${{ env.file_updated }}"

    - name: Setup git config
      if: ${{ env.FILE_UPDATED == 'true' }}
      shell: bash
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit changes
      if: ${{ env.FILE_UPDATED == 'true' }}
      shell: bash
      run: |
        git status
        git add .
        git commit -m "chore: Sync version.txt and .CSProj [skip ci]"
        git push origin ${{ inputs.branch }}
