name: 🎡 CI
on:
  push:
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: equinor/spine-splinter/.github/workflows/build.yml@main
    
  deploy-dev:
    name: "🚀 Dev"
    needs: build
    permissions:
      id-token: write
      contents: read
    uses: equinor/spine-splinter/.github/workflows/deploy.yml@main
    with:
      ENV: dev
      ARTIFACT: ${{ needs.build.outputs.artifact-name }}
      SKU: 'P1v2'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
