name: Sync issue to Azure DevOps work item

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: '${{ secrets.AZURE_DEVOPS_PAT }}'
          github_token: '${{ secrets.GH_TOKEN_ISSUES }}'
          ado_organization: 'EquinorASA'
          ado_project: 'Spine'
          ado_area_path: "Spine\\User Value Delivery\\Dugtrio"
          ado_iteration_path: "Spine\\Value Delivery"
          ado_wit: 'User Story'
          ado_new_state: 'New'
          ado_active_state: 'Active'
          ado_close_state: 'Closed'
          ado_bypassrules: true
          log_level: 100
