name: PR Code Validation
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate_code:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: "7.x.x"
      - name: Restore dependencies
        run: dotnet restore -r linux-x64 IntoRdf.sln
      - name: Build Solution
        run: dotnet build /p:TreatWarningsAsErrors="true" --no-restore --configuration Release IntoRdf.sln
      - name: Tests
        run: dotnet test --no-restore --no-build --filter UnitTests --configuration Release IntoRdf.sln
