name: Publish

on:
  workflow_dispatch:  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore IntoRdf
    - name: Build
      run: dotnet build IntoRdf -c release --no-restore
    - name: Publish
      run: dotnet nuget push ./IntoRdf/bin/release/IntoRdf*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}  --source https://api.nuget.org/v3/index.json
